// Generated by gve api generate. Do not edit manually.
package auth

type AuthItem struct {
	ID int64 `json:"id"`
	Email string `json:"email"`
	Name string `json:"name"`
	Mustchangepassword bool `json:"mustChangePassword"`
}

type GetCurrentUserRequest struct {
}

type GetCurrentUserResponse struct {
	User AuthItem `json:"user"`
}

type SetupStatusResponse struct {
	Needspasswordchange bool `json:"needsPasswordChange"`
}

type ChangePasswordRequest struct {
	Password string `json:"password"`
	Passwordconfirm string `json:"passwordConfirm"`
}

type ChangePasswordResponse struct {
	Success bool `json:"success"`
}

type AppInfoResponse struct {
	Mindpath string `json:"mindPath"`
}
