// Generated by gve api generate. Do not edit manually.
export class SearchServiceClient {
  private readonly baseUrl: string;

  constructor(baseUrl: string) {
    this.baseUrl = baseUrl;
  }

  async Search(reqBody: unknown): Promise<unknown[]> {
    const response = await fetch(`${this.baseUrl}/Search`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(reqBody),
    });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(`request failed: status=${response.status}, body=${text}`);
    }

    return (await response.json()) as unknown[];
  }
}
