// Generated by gve api generate. Do not edit manually.
package search

type SearchRequest struct {
	Query string `json:"query"`
}

type SearchResult struct {
	Path string `json:"path"`
	Name string `json:"name"`
	Matches []string `json:"matches"`
}
