// Generated by gve api generate. Do not edit manually.
export class AuthServiceClient {
  private readonly baseUrl: string;

  constructor(baseUrl: string) {
    this.baseUrl = baseUrl;
  }

  async GetCurrentUser(reqBody: unknown): Promise<unknown> {
    const response = await fetch(`${this.baseUrl}/GetCurrentUser`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(reqBody),
    });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(`request failed: status=${response.status}, body=${text}`);
    }

    return (await response.json()) as unknown;
  }

  async GetSetupStatus(reqBody: unknown): Promise<unknown> {
    const response = await fetch(`${this.baseUrl}/GetSetupStatus`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(reqBody),
    });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(`request failed: status=${response.status}, body=${text}`);
    }

    return (await response.json()) as unknown;
  }

  async ChangePassword(reqBody: unknown): Promise<unknown> {
    const response = await fetch(`${this.baseUrl}/ChangePassword`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(reqBody),
    });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(`request failed: status=${response.status}, body=${text}`);
    }

    return (await response.json()) as unknown;
  }

  async GetAppInfo(reqBody: unknown): Promise<unknown> {
    const response = await fetch(`${this.baseUrl}/GetAppInfo`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(reqBody),
    });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(`request failed: status=${response.status}, body=${text}`);
    }

    return (await response.json()) as unknown;
  }
}
