// Generated by gve api generate. Do not edit manually.
export class SpaceServiceClient {
  private readonly baseUrl: string;

  constructor(baseUrl: string) {
    this.baseUrl = baseUrl;
  }

  async ListSpaces(reqBody: unknown): Promise<unknown[]> {
    const response = await fetch(`${this.baseUrl}/ListSpaces`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(reqBody),
    });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(`request failed: status=${response.status}, body=${text}`);
    }

    return (await response.json()) as unknown[];
  }

  async CreateSpace(reqBody: unknown): Promise<unknown> {
    const response = await fetch(`${this.baseUrl}/CreateSpace`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(reqBody),
    });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(`request failed: status=${response.status}, body=${text}`);
    }

    return (await response.json()) as unknown;
  }

  async UpdateSpace(reqBody: unknown): Promise<unknown> {
    const response = await fetch(`${this.baseUrl}/UpdateSpace`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(reqBody),
    });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(`request failed: status=${response.status}, body=${text}`);
    }

    return (await response.json()) as unknown;
  }

  async DeleteSpace(reqBody: unknown): Promise<unknown> {
    const response = await fetch(`${this.baseUrl}/DeleteSpace`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(reqBody),
    });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(`request failed: status=${response.status}, body=${text}`);
    }

    return (await response.json()) as unknown;
  }

  async GetSpace(reqBody: unknown): Promise<unknown> {
    const response = await fetch(`${this.baseUrl}/GetSpace`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(reqBody),
    });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(`request failed: status=${response.status}, body=${text}`);
    }

    return (await response.json()) as unknown;
  }

  async GetDefaultSpace(reqBody: unknown): Promise<unknown> {
    const response = await fetch(`${this.baseUrl}/GetDefaultSpace`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(reqBody),
    });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(`request failed: status=${response.status}, body=${text}`);
    }

    return (await response.json()) as unknown;
  }
}
