// Generated by gve api generate. Do not edit manually.
export class DocsServiceClient {
  private readonly baseUrl: string;

  constructor(baseUrl: string) {
    this.baseUrl = baseUrl;
  }

  async GetConfig(reqBody: unknown): Promise<unknown> {
    const response = await fetch(`${this.baseUrl}/GetConfig`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(reqBody),
    });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(`request failed: status=${response.status}, body=${text}`);
    }

    return (await response.json()) as unknown;
  }

  async GetPage(reqBody: unknown): Promise<unknown> {
    const response = await fetch(`${this.baseUrl}/GetPage`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(reqBody),
    });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(`request failed: status=${response.status}, body=${text}`);
    }

    return (await response.json()) as unknown;
  }
}
