// Generated by gve api generate. Do not edit manually.
export class FileServiceClient {
  private readonly baseUrl: string;

  constructor(baseUrl: string) {
    this.baseUrl = baseUrl;
  }

  async GetTree(reqBody: unknown): Promise<unknown[]> {
    const response = await fetch(`${this.baseUrl}/GetTree`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(reqBody),
    });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(`request failed: status=${response.status}, body=${text}`);
    }

    return (await response.json()) as unknown[];
  }

  async GetFile(reqBody: unknown): Promise<unknown> {
    const response = await fetch(`${this.baseUrl}/GetFile`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(reqBody),
    });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(`request failed: status=${response.status}, body=${text}`);
    }

    return (await response.json()) as unknown;
  }

  async SaveFile(reqBody: unknown): Promise<unknown> {
    const response = await fetch(`${this.baseUrl}/SaveFile`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(reqBody),
    });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(`request failed: status=${response.status}, body=${text}`);
    }

    return (await response.json()) as unknown;
  }

  async CreateFile(reqBody: unknown): Promise<unknown> {
    const response = await fetch(`${this.baseUrl}/CreateFile`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(reqBody),
    });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(`request failed: status=${response.status}, body=${text}`);
    }

    return (await response.json()) as unknown;
  }

  async DeleteFile(reqBody: unknown): Promise<unknown> {
    const response = await fetch(`${this.baseUrl}/DeleteFile`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(reqBody),
    });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(`request failed: status=${response.status}, body=${text}`);
    }

    return (await response.json()) as unknown;
  }

  async RenameFile(reqBody: unknown): Promise<unknown> {
    const response = await fetch(`${this.baseUrl}/RenameFile`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(reqBody),
    });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(`request failed: status=${response.status}, body=${text}`);
    }

    return (await response.json()) as unknown;
  }
}
