// Generated by gve api generate. Do not edit manually.
package docs

type TopbarLink struct {
	Label string `json:"label"`
	Href string `json:"href"`
	External bool `json:"external,omitempty"`
}

type DocsSite struct {
	Title string `json:"title"`
	Root string `json:"root"`
	Homepage string `json:"homepage"`
	Defaultlayout string `json:"defaultLayout,omitempty"`
	Defaultcontentmode string `json:"defaultContentMode,omitempty"`
}

type DocsTopbar struct {
	Showsearch bool `json:"showSearch"`
	Links []TopbarLink `json:"links,omitempty"`
}

type DocsPageRef struct {
	ID string `json:"id"`
	Title string `json:"title,omitempty"`
	Hidden bool `json:"hidden,omitempty"`
	Layout string `json:"layout,omitempty"`
	Contentmode string `json:"contentMode,omitempty"`
}

type DocsGroup struct {
	Key string `json:"key"`
	Label string `json:"label"`
	Pages []DocsPageRef `json:"pages"`
}

type DocsTab struct {
	Key string `json:"key"`
	Label string `json:"label"`
	Groups []DocsGroup `json:"groups"`
}

type DocsConfigResponse struct {
	Site DocsSite `json:"site"`
	Topbar DocsTopbar `json:"topbar"`
	Tabs []DocsTab `json:"tabs"`
}

type GetPageRequest struct {
	ID string `json:"id"`
}

type DocsPageResponse struct {
	ID string `json:"id"`
	Title string `json:"title"`
	Description string `json:"description,omitempty"`
	Toc bool `json:"toc"`
	Layout string `json:"layout"`
	Contentmode string `json:"contentMode"`
	Content string `json:"content"`
}
