// Generated by gve api generate. Do not edit manually.
package file

type FileTreeItem struct {
	Name string `json:"name"`
	Path string `json:"path"`
	Type string `json:"type"`
	Children []FileTreeItem `json:"children,omitempty"`
}

type FileContentResponse struct {
	Content string `json:"content"`
	Path string `json:"path"`
}

type GetFileRequest struct {
	Path string `json:"path"`
}

type SaveFileRequest struct {
	Path string `json:"path"`
	Content string `json:"content"`
}

type CreateFileRequest struct {
	Path string `json:"path"`
	Type string `json:"type"`
	Name string `json:"name"`
}

type DeleteFileRequest struct {
	Path string `json:"path"`
}

type RenameFileRequest struct {
	Path string `json:"path"`
	NewName string `json:"new_name"`
}

type MutationResponse struct {
	Success bool `json:"success"`
	Path string `json:"path,omitempty"`
}
